module.exports = {
    LIGHT_UNICOLOR_DIMMABLE: 'LIGHT_UNICOLOR_DIMMABLE',
    LIGHT_UNICOLOR_NONDIMMABLE: 'LIGHT_UNICOLOR_NONDIMMABLE',
    LIGHT_MULTICOLOR: 'LIGHT_MULTICOLOR',
    SWITCH: 'SWITCH',
}